const fs=require('node:fs'),assert=require('node:assert/strict');
const object=require('./wardrobe_object_ui.cjs'),rewrite=require('./wardrobe_continuation_ui.cjs'),dynamic=require('./wardrobe_dynamic_ui.cjs');
const read=name=>fs.readFileSync(require('node:path').join(__dirname,'../web/',name),'utf8');
async function attach(t){
 let holdNext=false,release=null;const previewRequests=[];
 const w=t.w,old=w.fetch;w.HTMLElement.prototype.scrollIntoView=function(){};
 w.fetch=async(url,opts)=>{
  if(url==='/api/inline-cast/prompt-preview'){
   const body=JSON.parse(opts.body);previewRequests.push(body);
   const result={count:body.people.length+1,image_count:2+body.people.length*2,final_prompt:`${body.people.length+1}人规则：${body.custom||JSON.stringify(body.segments)}`,white_prompt:`${body.people.length+1}人红白模规则：${body.white_extra||''}`};
   if(holdNext){holdNext=false;await new Promise(resolve=>release=resolve);}
   return {ok:true,json:async()=>result};
  }
  if(url.startsWith('/api/character-library?'))return {ok:true,json:async()=>({configured:true,groups:[{id:'group-images',name:'人物组',group_type:'AIGC'}],assets:[1,2,3].map(i=>({uri:'asset://asset-person00000'+i,id:'asset-person00000'+i,name:'人物图片'+i,url:'https://example.test/person'+i+'.png',asset_type:'Image',status:'Active',group_id:'group-images'}))})};
  return old(url,opts);
 };
 w.eval(read('character_library.js'));w.eval(read('inline_cast.js'));await object.tick();
 w.DepthFlowInlineCast.restore({id:'restored',inline_cast:[]});
 w.document.dispatchEvent(new w.Event('inline-cast-change'));
 const q=s=>w.document.querySelector(s);
 const select=n=>q(`[data-character-select="asset://asset-person00000${n}"]`).click();
 const add=()=>q('[data-cast-add]').click();
 const cloth=(index=1)=>{const input=w.document.querySelectorAll('[data-cast-clothing]')[index-1];Object.defineProperty(input,'files',{configurable:true,value:[new w.File(['cloth'],'cloth.png',{type:'image/png'})]});input.dispatchEvent(new w.Event('change'));};
 return {q,select,add,cloth,previewRequests,hold:()=>{holdNext=true;},release:()=>release?.()};
}
async function run(){
 function replacePeople(t,a){
  const cards=()=>[...t.w.document.querySelectorAll('.inline-cast article')];
  const choose=i=>cards()[i].querySelector('[data-cast-choose]').click();
  const clothingPreview=cards()[1].querySelector('[data-cast-clothing-preview]').src;
  a.q('[data-character-source-mode="upload"]').click();
  choose(0);
  assert.equal(a.q('[data-character-existing-pane]').classList.contains('hidden'),false,'changing a person must open the role choices, even after using the upload pane');
  assert.match(a.q('.shared-character-library h3').textContent,/人物1/);
  assert.equal(t.$('personAsset').value,'asset://asset-person000001','opening the chooser must preserve the current person');
  a.select(3);
  assert.equal(t.$('personAsset').value,'asset://asset-person000003');
  assert.match(cards()[0].querySelector('[data-cast-person-preview]').src,/person3.png/);
  assert.match(cards()[1].querySelector('[data-cast-person-preview]').src,/person2.png/);
  assert.equal(cards()[0].querySelector('[data-cast-choose]').textContent,'更换人物');
  assert.equal(t.w.document.activeElement,cards()[0].querySelector('[data-cast-choose]'),'return to the updated card after choosing');
  cards()[1].querySelector('[data-cast-upload]').click();
  assert.equal(a.q('[data-character-upload-pane]').classList.contains('hidden'),false);
  assert.match(a.q('.shared-character-library h3').textContent,/人物2/);
  choose(1);a.select(1);
  assert.equal(t.$('personAsset').value,'asset://asset-person000003','changing the second person must preserve the first');
  assert.match(cards()[1].querySelector('[data-cast-person-preview]').src,/person1.png/);
  assert.equal(cards()[1].querySelector('[data-cast-clothing-preview]').src,clothingPreview,'changing identity must preserve clothing');
 }
 for(const mode of ['dynamic_object','dynamic_scene']){
  const t=await object.setup({mode,workflow:'references',restore:true}),{w,$}=t,a=await attach(t);
  a.select(1);a.add();a.select(2);a.cloth();
  assert.equal($('personAsset').value,'asset://asset-person000001','second-person selection must not overwrite first');
  assert.match(a.q('article[data-id] [data-cast-person-preview]').src,/person1.png/);
  assert.equal(w.document.querySelectorAll('.inline-cast article').length,2);
  replacePeople(t,a);
  t.setFile('objectClothing');t.setFile('objectItem');$('objectWhiteReviewed').checked=true;t.change('objectWhiteReviewed');
  t.input('objectPrompt','替换成@图片3，第二个人@图片4穿@图片5');
  await object.tick();
  assert.equal($('inlineFinalPromptPreview').hidden,false);
  assert.match($('inlineFinalPromptPreview').textContent,/2人规则/);
  assert.match($('inlineFinalPromptPreview').querySelector('pre').textContent,/@图片4穿@图片5/);
  assert.equal(a.previewRequests.at(-1).mode,mode);
  assert.equal(a.previewRequests.at(-1).people[0].has_clothing,true);
  assert.equal($('objectPrompt').value,'替换成@图片3，第二个人@图片4穿@图片5','preview must preserve custom input');
  assert.equal($('objectWhiteBase').classList.contains('inline-prompt-superseded'),true);
  assert.equal($('inlineWhitePromptPreview').parentElement,$('objectWhiteBase').parentElement,'colored rules must appear inside the original white-prompt section');
  a.hold();t.input('objectPrompt','旧要求');await object.tick();
  t.input('objectPrompt','新要求');await object.tick();a.release();await object.tick();
  assert.match($('inlineFinalPromptPreview').querySelector('pre').textContent,/新要求/);
  assert.doesNotMatch($('inlineFinalPromptPreview').querySelector('pre').textContent,/旧要求/);
  t.input('objectPrompt','替换成@图片3，第二个人@图片4穿@图片5');
  assert.equal($('objectGenerateBtn').disabled,false,$('objectGenerateHint').textContent);
  $('objectGenerateBtn').click();await object.tick();await t.confirm();
  const post=t.posts.find(p=>p.url==='/api/wardrobe-swap/generate');assert.ok(post);
  const people=JSON.parse(post.body.get('additional_people'));assert.equal(people[0].uri,'asset://asset-person000001');
  assert.equal(post.body.get('person_asset'),'asset://asset-person000003');
  assert.equal(post.body.get('additional_clothing_'+people[0].id).name,'cloth.png');
  // Moving/deleting bindings cannot silently reassign @ tokens to a different person.
  a.add();a.select(3);const input=$('objectPrompt');input.value='第二个人@图片4服装@图片5第三个人@图片6';
  w.document.querySelector('[data-cast-clear-clothing]').click();
  assert.equal(input.value,'第二个人@图片4服装@已移除人物参考第三个人@图片5');
  w.DepthFlowInlineCast.restore({id:'unrelated-source',inline_cast:[]});w.document.dispatchEvent(new w.Event('inline-cast-change'));await object.tick();assert.equal(w.DepthFlowInlineCast.count(),1);assert.equal($('inlineFinalPromptPreview').hidden,true);assert.equal($('objectWhiteBase').classList.contains('inline-prompt-superseded'),false);
  w.DepthFlowInlineCast.restore({id:'proxy-before-references',inline_cast:[],inline_color_plan:[{id:'p1',color:'red'},{id:'p2',color:'white',source:'右侧人物'}]},true);
  w.document.dispatchEvent(new w.Event('inline-cast-change'));await object.tick();
  assert.equal(w.DepthFlowInlineCast.count(),2,'refreshing a two-person proxy must restore two slots even without saved reference images');
  assert.equal($('inlineWhitePromptPreview').hidden,false);
  assert.match($('inlineWhitePromptPreview').textContent,/2人红白模/);
  const labels=()=>[...w.document.querySelectorAll('.inline-cast article>b')].map(b=>b.textContent);
  a.add();await object.tick();
  assert.deepEqual(labels(),['人物1 · 红模','人物2 · 白模','人物3 · 黄模']);
  assert.match(w.DepthFlowInlineCast.problem(),/当前母版为 2 人/);
  a.add();await object.tick();
  assert.deepEqual(labels(),['人物1 · 红模','人物2 · 白模','人物3 · 黄模','人物4 · 蓝模']);
  const oldPlan=['red','white','blue','yellow'].map((color,i)=>({id:'p'+(i+1),color,source:''}));
  w.DepthFlowInlineCast.restore({id:'old-four-person-master',inline_cast:[],inline_color_plan:oldPlan},true);
  w.document.dispatchEvent(new w.Event('inline-cast-change'));await object.tick();
  assert.deepEqual(labels(),['人物1 · 红模','人物2 · 白模','人物3 · 蓝模','人物4 · 黄模'],'existing masters retain their actual color bindings');
  assert.deepEqual(a.previewRequests.at(-1).color_plan,oldPlan);
  const newPlan=['red','white','yellow','blue'].map((color,i)=>({id:'p'+(i+1),color,source:''}));
  w.DepthFlowInlineCast.restore({id:'old-four-person-master',inline_cast:[],inline_color_plan:newPlan});
  await object.tick();
  assert.deepEqual(labels(),['人物1 · 红模','人物2 · 白模','人物3 · 黄模','人物4 · 蓝模'],'regenerating the current master updates the colors without losing person slots');
  assert.deepEqual(a.previewRequests.at(-1).color_plan,newPlan);
  t.close();
 }
 const t=await rewrite.setup({workflow:'references'}),a=await attach(t),{w,$}=t;
 a.select(1);a.add();a.select(2);a.cloth();
 replacePeople(t,a);
 Object.defineProperty($('clothingFile'),'files',{value:[new w.File(['first'],'first.png')],configurable:true});
 $('mosaicReviewed').checked=true;t.review();t.input(0,'.range-prompt','人物2参考@图片3，服装@图片4');
 assert.equal($('generateBtn').disabled,false,$('generateReason').textContent);
 $('generateBtn').click();await rewrite.tick();await t.confirm();
 assert.equal(JSON.parse(t.posts.at(-1).body.get('additional_people'))[0].uri,'asset://asset-person000001');
 assert.equal(t.posts.at(-1).body.get('person_asset'),'asset://asset-person000003');
 assert.equal(t.posts.at(-1).body.get('generation_mode'),'full_video');t.close();
 const d=dynamic.setup({restore:true});await dynamic.tick();const da=await attach(d);
 da.select(1);da.add();da.select(2);da.cloth();replacePeople(d,da);
 await dynamic.tick();
 assert.equal(d.$('inlineWhitePromptPreview').parentElement,d.$('dynamicWhiteBase').parentElement);
 assert.match(d.$('dynamicWhiteControls').querySelector('summary').textContent,/2 人分色/);
 assert.match(d.$('whiteDescription').textContent,/不保留衣服/);
 da.add();await dynamic.tick();
 assert.match(d.$('whiteDescription').textContent,/红、白、黄分色/);
 da.add();await dynamic.tick();
 assert.match(d.$('whiteDescription').textContent,/红、白、黄、蓝分色/);
 for(let i=0;i<2;i++)[...d.w.document.querySelectorAll('[data-cast-remove]')].at(-1).click();
 d.setFile('newClothingImage','first.png');d.$('dynamicWhiteReviewed').checked=true;d.change('dynamicWhiteReviewed');
 assert.equal(d.$('generateBtn').disabled,false,d.$('generateReason').textContent);
 d.$('generateBtn').click();await dynamic.tick();await d.confirm();
 assert.equal(d.posts.at(-1).body.get('person_asset'),'asset://asset-person000003');
 assert.equal(JSON.parse(d.posts.at(-1).body.get('additional_people'))[0].uri,'asset://asset-person000001');d.close();
 const optional=dynamic.setup({restore:true});await dynamic.tick();const oa=await attach(optional);
 oa.select(1);oa.add();oa.select(2);oa.cloth();
 const cards=()=>[...optional.w.document.querySelectorAll('.inline-cast article')];
 assert.equal(cards()[0].querySelector('#newClothingImage'),optional.$('newClothingImage'),'primary clothing belongs inside person 1');
 assert.equal(cards()[1].querySelectorAll('[data-cast-clothing]').length,1);
 let picked=false;optional.$('newClothingImage').addEventListener('click',()=>{picked=true;});
 cards()[0].querySelector('[data-primary-clothing-change]').click();assert.equal(picked,true);
 optional.setFile('newClothingImage','primary-outfit.png');await dynamic.tick();
 assert.match(cards()[0].querySelector('[data-primary-clothing-preview]').src,/blob:/);
 optional.$('prompt').value='人物1服装@图片2，人物2@图片3服装@图片4';
 cards()[0].querySelector('[data-primary-clothing-clear]').click();await dynamic.tick();
 assert.equal(optional.w.DepthFlowInlineCast.hasClothing(),false);
 assert.equal(optional.$('prompt').value,'人物1服装@已移除人物参考，人物2@图片2服装@图片3');
 optional.$('prompt').value='人物2@图片2穿@图片3';optional.$('prompt').dispatchEvent(new optional.w.Event('input'));
 optional.$('dynamicWhiteReviewed').checked=true;optional.change('dynamicWhiteReviewed');await dynamic.tick();
 assert.equal(optional.$('generateBtn').disabled,false,optional.$('generateReason').textContent);
 assert.equal(oa.previewRequests.at(-1).first_clothing,false);
 optional.$('generateBtn').click();await dynamic.tick();await optional.confirm();
 assert.equal(optional.posts.at(-1).body.get('primary_clothing_state'),'none');
 assert.equal(optional.posts.at(-1).body.has('primary_clothing_image'),false);
 optional.close();
 console.log('Inline people: optional per-person clothing, replacement/deletion, separate previews/uploads, FormData bindings and safe mention remapping passed.');
}
run().catch(e=>{console.error(e);process.exitCode=1;});
