// Exercise the two background workflows with mocked HTTP; no paid work or uploads.
const assert = require('node:assert/strict');
const {setup,tick} = require('./wardrobe_object_ui.cjs');

async function run() {
  const t=await setup({mode:'dynamic_scene'}), {$,w}=t;
  assert.equal($('objectLibrarySource').classList.contains('hidden'),false);
  assert.equal($('objectActorReferences').classList.contains('hidden'),true);
  assert.equal($('objectPrepare').classList.contains('hidden'),true);
  assert.match($('objectWhiteBase').textContent,/绿底白模/);
  assert.match($('objectGenerateBtn').textContent,/背景替换/);
  t.input('objectVideoGroup','group-123456789');t.change('objectVideoGroup');
  t.input('objectVideoAsset','asset://asset-video123456');t.change('objectVideoAsset');
  const video=$('objectVideoAssets').querySelector('video');
  assert.equal(video.autoplay,true);assert.equal(video.muted,true);
  video.dispatchEvent(new w.Event('loadeddata'));assert.match($('objectVideoAssets').textContent,/画面已加载/);
  $('objectVideoAssets').querySelector('button').click();await tick();
  assert.equal(t.posts.at(-1).url,'/api/wardrobe-scene/select-video');
  t.input('objectPrompt','将海边背景换成森林');assert.equal($('objectGenerateBtn').disabled,false);
  assert.equal($('objectBindings').children.length,1);
  $('objectGenerateBtn').click();await tick();await t.confirm();
  let body=t.posts.at(-1).body;
  assert.equal(body.get('mode'),'dynamic_scene');
  assert.equal(body.has('person_asset'),false);assert.equal(body.has('clothing_image'),false);assert.equal(body.has('replacement_image'),false);
  t.setFile('objectItem','scene.png');t.input('objectPrompt','换成 @');
  assert.equal($('objectMentions').children.length,2);$('objectMentions').children[1].click();
  assert.equal($('objectPrompt').value,'换成 @图片1');
  assert.match($('objectBindings').textContent,/@图片1 · 场景参考图/);
  $('objectGenerateBtn').click();await tick();await t.confirm();
  assert.equal(t.posts.at(-1).body.get('replacement_image').name,'scene.png');
  w.document.querySelector('[data-object-workflow="references"]').click();await tick();
  assert.equal($('objectPrepare').classList.contains('hidden'),false);
  assert.equal($('objectActorReferences').classList.contains('hidden'),false);
  assert.equal($('objectWhiteReviewed').checked,false);
  assert.match($('objectItemBinding').textContent,/必需.*@图片3/);
  assert.equal($('objectItem').files.length,0,'branch switch must clear previous scene image');
  t.setFile('objectOriginal','original.mp4');t.input('objectThreshold','.40');
  $('objectMosaic').click();await tick();
  body=t.posts.at(-1).body;assert.equal(body.get('mode'),'dynamic_scene');assert.equal(Number(body.get('face_score_threshold')),0.4);
  assert.equal($('objectMakeWhite').disabled,true);
  $('objectMosaicReviewed').checked=true;t.change('objectMosaicReviewed');
  $('objectMakeWhite').click();await tick();assert.match($('paidConfirmTitle').textContent,/绿底白模/);await t.confirm();
  assert.equal(t.posts.at(-1).body.get('mosaic_reviewed'),'true');
  t.input('personAsset','asset://asset-person123456');t.setFile('objectClothing','clothing.png');
  $('objectWhiteReviewed').checked=true;t.change('objectWhiteReviewed');t.input('objectPrompt','换成森林');
  assert.equal($('objectGenerateBtn').disabled,true);assert.match($('objectGenerateHint').textContent,/场景参考图/);
  t.setFile('objectItem','forest.png');t.input('objectPrompt','换成 @');
  assert.equal($('objectMentions').children.length,4);$('objectMentions').children[3].click();
  assert.equal($('objectPrompt').value,'换成 @图片3');assert.equal($('objectGenerateBtn').disabled,false);
  $('objectGenerateBtn').click();await tick();await t.confirm();body=t.posts.at(-1).body;
  assert.equal(body.get('person_asset'),'asset://asset-person123456');
  assert.equal(body.get('clothing_image').name,'clothing.png');assert.equal(body.get('replacement_image').name,'forest.png');
  $('objectClearItem').click();assert.equal($('objectGenerateBtn').disabled,true);
  assert.equal(w.localStorage.getItem('depthflow.scene.workflow'),'references');
  assert.equal(w.localStorage.getItem('depthflow.object.workflow'),'references');
  t.close();
  const restored=await setup({mode:'dynamic_scene',restore:true,workflow:'references'});
  assert.equal(restored.$('objectThreshold').value,'0.4');
  assert.equal(restored.$('objectGenerateBtn').disabled,true,'restored green proxy still requires review and references');
  restored.setFile('objectWhiteUpload','green-white.mp4');restored.$('objectImportWhite').click();await tick();
  assert.equal(restored.posts.at(-1).url,'/api/wardrobe-scene/import-white');
  assert.equal(restored.$('paidConfirmModal').hidden,true);restored.close();
  const old=await setup({mode:'dynamic_scene',oldServer:true});
  assert.equal(old.$('objectMosaic').disabled,true);assert.equal(old.$('objectGenerateBtn').disabled,true);
  assert.match(old.$('objectGenerateHint').textContent,/后台/);old.close();
  console.log('Background workflows: original video preview, optional scene, green proxy, required actor/clothing/scene, mentions, history and backend capability checks passed.');
}
run().catch(error=>{console.error(error);process.exitCode=1;});
