const state={config:null,sourceJobId:null,activeJobId:null,retryJobId:null,recoverSeedanceJobId:null,pollTimer:null,hasSavedClothing:false};
const $=(selector)=>document.querySelector(selector);
function toast(message,isError=false){const node=$("#toast");node.textContent=message;node.classList.toggle("error",isError);node.classList.add("show");clearTimeout(node._timer);node._timer=setTimeout(()=>node.classList.remove("show"),4200);}
async function api(url,options={}){const response=await fetch(url,options);let payload={};try{payload=await response.json();}catch(_error){}if(!response.ok)throw new Error(window.DepthFlowUI?.formatApiError?.(payload,response)||payload.error||payload.message||`请求失败（HTTP ${response.status}）`);return payload;}
function setBadge(selector,ready,yes,no){const badge=$(selector);badge.className=`badge ${ready?"ready":"missing"}`;badge.innerHTML=`<i></i>${ready?yes:no}`;}
function bindFile(input,label){$(input).addEventListener("change",()=>{const file=$(input).files[0];if(file)$(label).textContent=file.name;});}
function setBusy(busy){["#prepareBtn","#generateBtn","#fullBtn","#recoverBtn","#retryReferencesBtn","#recoverSeedanceBtn"].forEach(s=>$(s).disabled=busy);}
function appendExtraction(form){form.append("blur_range",$("#blurRange").value.trim());form.append("person_prompt",$("#personPrompt").value.trim());form.append("scene_prompt",$("#scenePrompt").value.trim());form.append("image_model",$("#imageModel").value.trim());}
function appendGeneration(form,allowSaved=false){const clothing=$("#clothingImage").files[0];if(!clothing&&!(allowSaved&&state.hasSavedClothing))throw new Error("请选择需要替换的新服装图片。");if(clothing)form.append("clothing_image",clothing);const personAsset=$("#personAsset")?.value.trim()||"";if(personAsset)form.append("person_asset",personAsset);form.append("prompt",$("#prompt").value.trim());form.append("model",$("#model").value.trim());form.append("resolution",$("#resolution").value);form.append("ratio",$("#ratio").value);form.append("duration",$("#duration").value);form.append("generate_audio",$("#generateAudio").checked?"true":"false");form.append("watermark",$("#watermark").checked?"true":"false");form.append("delete_tos_after",$("#deleteTos").checked?"true":"false");form.append("depth_reference",$("#depthReference").value.trim());}
function confirmPaid(mode){const messages={prepare:"即将调用 Seedream 两次：生成不含原片服装的16:9白色底衫人物三视图、重建原片干净场景。深度转换在本地完成。是否继续？",generate:"即将调用 Seedance 2.0，以@图片2作为唯一服装依据生成换装成片。是否继续？",full:"即将执行完整流程：白色底衫人物提取、场景提取、按新服装生成成片（2次 Seedream + 1次 Seedance）。是否继续？",retry:"将按白色底衫新规则补充人物或场景参考，可能产生1至2次 Seedream 调用。是否继续？"};return window.confirm(messages[mode]);}
async function prepare(){const video=$("#referenceVideo").files[0];if(!video)return toast("请先选择原视频。",true);if(!confirmPaid("prepare"))return;const form=new FormData();form.append("reference_video",video);appendExtraction(form);setBusy(true);try{const job=await api("/api/clothing-only/prepare",{method:"POST",body:form});state.sourceJobId=job.id;monitor(job.id,true);}catch(error){setBusy(false);toast(error.message,true);}}
async function generatePrepared(){try{if(!state.sourceJobId)throw new Error("请先准备深度、人物与场景参考。");const form=new FormData();form.append("source_job_id",state.sourceJobId);appendGeneration(form,true);if(!confirmPaid("generate"))return;setBusy(true);const job=await api("/api/clothing-only/generate",{method:"POST",body:form});monitor(job.id);}catch(error){setBusy(false);toast(error.message,true);}}
async function full(){try{const video=$("#referenceVideo").files[0];if(!video)throw new Error("请选择原视频。");const form=new FormData();form.append("reference_video",video);appendExtraction(form);appendGeneration(form);if(!confirmPaid("full"))return;setBusy(true);const job=await api("/api/clothing-only/full",{method:"POST",body:form});monitor(job.id);}catch(error){setBusy(false);toast(error.message,true);}}
async function retryReferences(){if(!state.retryJobId)return toast("没有可重试的参考提取。",true);if(!confirmPaid("retry"))return;const form=new FormData();form.append("source_job_id",state.retryJobId);appendExtraction(form);setBusy(true);try{const job=await api("/api/clothing-only/retry-references",{method:"POST",body:form});monitor(job.id,true);}catch(error){setBusy(false);toast(error.message,true);}}
async function recoverSeedance(){if(!state.recoverSeedanceJobId)return;const form=new FormData();form.append("source_job_id",state.recoverSeedanceJobId);["model","resolution","ratio","duration"].forEach(id=>form.append(id,$(`#${id}`).value));form.append("generate_audio",$("#generateAudio").checked?"true":"false");setBusy(true);try{const job=await api("/api/clothing-only/recover-seedance",{method:"POST",body:form});monitor(job.id);}catch(error){setBusy(false);toast(error.message,true);}}
function loadVideo(selector,url,key){const video=$(selector);if(video.dataset.key===key)return;video.src=`${url}?preview=${encodeURIComponent(key)}`;video.dataset.key=key;video.load();}
function loadImage(selector,url,key){const image=$(selector);if(image.dataset.key===key)return;image.src=`${url}?preview=${encodeURIComponent(key)}`;image.dataset.key=key;}
function setDownload(selector,url,name){const link=$(selector);link.href=`${url}?download=1`;link.dataset.downloadUrl=url;link.dataset.suggestedName=name;}
function render(job,preparationOnly=false){$("#emptyTask").classList.add("hidden");$("#activeTask").classList.remove("hidden");$("#jobKind").textContent=({clothing_prepare:"人物场景准备",clothing_generate:"服装替换成片",clothing_full:"一键服装替换"})[job.kind]||"只更换服装";$("#jobStage").textContent=job.stage;$("#cloudTaskId").textContent=job.task_id?`Seedance 任务 ID：${job.task_id}`:`本地任务：${job.id}`;$("#progressPercent").textContent=`${job.progress}%`;$("#progressBar").style.width=`${job.progress}%`;$("#jobLogs").textContent=job.logs.join("\n");$("#jobLogs").scrollTop=$("#jobLogs").scrollHeight;if(job.generation_duration){$("#duration").value=job.generation_duration;$("#durationHint").textContent=`原片自动匹配 → ${job.generation_duration} 秒`;}
  const retry=job.status==="failed"&&job.recovery_action==="retry_clothing_references";$("#referenceRetryArea").classList.toggle("hidden",!retry);state.retryJobId=retry?job.id:null;const recover=job.status==="failed"&&job.recovery_action==="recover_seedance_submission";$("#seedanceRecoverArea").classList.toggle("hidden",!recover);state.recoverSeedanceJobId=recover?job.id:null;state.hasSavedClothing=Boolean(job.has_clothing_reference);
  const areas=[["depth","#depthResultArea","#depthResultVideo","#depthDownloadLink","深度视频","video"],["person","#personResultArea","#personResultImage","#personDownloadLink","原人物三视图","image"],["clothing","#clothingResultArea","#clothingResultImage","#clothingDownloadLink","新服装参考","image"],["scene","#sceneResultArea","#sceneResultImage","#sceneDownloadLink","原片干净场景","image"]];for(const [kind,area,media,link,name,type] of areas){const has=Boolean(job[`has_${kind==="person"?"person_reference":kind==="clothing"?"clothing_reference":kind}`]);$(area).classList.toggle("hidden",!has);if(has){const url=job[`${kind}_url`];const key=`${job.id}-${kind}-${job.created_at}`;type==="video"?loadVideo(media,url,key):loadImage(media,url,key);setDownload(link,url,`${name}_${job.id}.${type==="video"?"mp4":"jpg"}`);}}
  if(job.has_depth&&job.has_person_reference&&job.has_scene){state.sourceJobId=job.id;$("#prepareState").textContent="深度、原人物与原场景均已准备完成";}
  const finalVisible=!preparationOnly&&(["clothing_generate","clothing_full","query"].includes(job.kind))&&(job.has_output||job.task_id||job.cloud_status||job.progress>=55);$("#finalResultArea").classList.toggle("hidden",!finalVisible);$("#finalResultVideo").classList.toggle("hidden",!job.has_output);$("#finalResultActions").classList.toggle("hidden",!job.has_output);$("#seedanceLivePreview").classList.toggle("hidden",job.has_output||!finalVisible);if(job.has_output){loadVideo("#finalResultVideo",job.output_url,`${job.id}-output-${job.created_at}`);setDownload("#finalDownloadLink",job.output_url,`只更换服装成片_${job.id}.mp4`);$("#seedancePreviewCaption").textContent="服装替换完成";}else if(finalVisible){$("#seedanceProgressPercent").textContent=`${job.progress}%`;$("#seedanceProgressBar").style.width=`${job.progress}%`;$("#seedanceCloudStatus").textContent=job.stage;$("#seedanceProgressNote").textContent=job.progress_estimated?"官方状态已同步，百分比为阶段估算":"正在同步任务阶段";}$("#resultArea").classList.toggle("hidden",!(job.has_depth||job.has_person_reference||job.has_scene||job.has_clothing_reference||finalVisible));}
function monitor(id,preparationOnly=false){state.activeJobId=id;clearInterval(state.pollTimer);const poll=async()=>{try{const job=await api(`/api/jobs/${id}`);render(job,preparationOnly);if(["succeeded","failed","submitted"].includes(job.status)){clearInterval(state.pollTimer);setBusy(false);toast(job.status==="succeeded"?(preparationOnly?"人物与场景参考已准备完成。":"服装替换成片已完成。"):(window.DepthFlowUI?.formatJobError?.(job)||job.error||"任务失败。"),job.status==="failed");}}catch(error){clearInterval(state.pollTimer);setBusy(false);toast(error.message,true);}};poll();state.pollTimer=setInterval(poll,1800);$(".task-panel").scrollIntoView({behavior:"smooth",block:"start"});}
async function recoverTask(){const taskId=$("#recoverTaskId").value.trim();if(!taskId)return toast("请输入 Seedance 任务 ID。",true);setBusy(true);try{const job=await api("/api/query",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task_id:taskId,project:"clothing_only_replacement",source_job_id:state.sourceJobId||""})});monitor(job.id);}catch(error){setBusy(false);toast(error.message,true);}}
async function openFolder(){if(!state.activeJobId)return;try{await api(`/api/jobs/${state.activeJobId}/open-folder`,{method:"POST"});}catch(error){toast(error.message,true);}}
async function saveLink(event,selector,defaultName,type){event.preventDefault();const link=$(selector),url=link.dataset.downloadUrl;if(!url)return;const name=link.dataset.suggestedName||defaultName;if(typeof window.showSaveFilePicker!=="function"){const a=document.createElement("a");a.href=`${url}?download=1`;a.download=name;a.click();return;}try{const handle=await window.showSaveFilePicker({suggestedName:name,types:[type==="image"?{description:"图片",accept:{"image/jpeg":[".jpg",".jpeg"]}}:{description:"MP4 视频",accept:{"video/mp4":[".mp4"]}}]});const response=await fetch(url);const writable=await handle.createWritable();if(response.body)await response.body.pipeTo(writable);else{await writable.write(await response.blob());await writable.close();}toast(`已保存：${handle.name}`);}catch(error){if(error?.name!=="AbortError")toast(error.message,true);}}
async function loadConfig(){try{const config=await api("/api/config");state.config=config;$("#personPrompt").value=config.clothing_person_triview_prompt;$("#scenePrompt").value=config.scene_prompt;$("#prompt").value=config.clothing_only_prompt;$("#model").value=config.model;$("#imageModel").value=config.image_model;setBadge("#arkBadge",config.ark_ready,"API 已配置","API 未配置");setBadge("#channelBadge",config.temporary_upload_ready,"免费临时通道可用","临时通道不可用");if(config.latest_cloud?.project==="clothing_only_replacement")render(config.latest_cloud);else if(config.latest_clothing_only){render(config.latest_clothing_only,!config.latest_clothing_only.has_output);}}catch(error){toast(error.message,true);}}
bindFile("#referenceVideo","#videoFileName");bindFile("#clothingImage","#clothingFileName");$("#referenceVideo").addEventListener("change",()=>{const file=$("#referenceVideo").files[0];if(!file)return;const video=document.createElement("video"),url=URL.createObjectURL(file);video.onloadedmetadata=()=>{$("#duration").value=Math.min(15,Math.max(4,Math.floor(Math.min(video.duration,14.5)+.5)));$("#durationHint").textContent=`原片 ${video.duration.toFixed(2)} 秒 → 自动匹配`;URL.revokeObjectURL(url);};video.src=url;});
$("#prepareBtn").addEventListener("click",prepare);$("#generateBtn").addEventListener("click",generatePrepared);$("#fullBtn").addEventListener("click",full);$("#retryReferencesBtn").addEventListener("click",retryReferences);$("#recoverSeedanceBtn").addEventListener("click",recoverSeedance);$("#recoverBtn").addEventListener("click",recoverTask);$("#openFolderBtn").addEventListener("click",openFolder);$("#resetPersonPromptBtn").addEventListener("click",()=>$("#personPrompt").value=state.config.clothing_person_triview_prompt);$("#resetScenePromptBtn").addEventListener("click",()=>$("#scenePrompt").value=state.config.scene_prompt);$("#resetPromptBtn").addEventListener("click",()=>$("#prompt").value=state.config.clothing_only_prompt);[["#depthDownloadLink","深度视频.mp4","video"],["#personDownloadLink","白色底衫人物三视图.jpg","image"],["#clothingDownloadLink","新服装.jpg","image"],["#sceneDownloadLink","原场景.jpg","image"],["#finalDownloadLink","换装成片.mp4","video"]].forEach(([selector,name,type])=>$(selector).addEventListener("click",event=>saveLink(event,selector,name,type)));loadConfig();
